### PR TITLE
Replace Existing Textures with Pap's Scaled RSS Textures

### PR DESCRIPTION
**Pull request by Bornholio**
NOTE: CHANGE \RSS-Textures\bin\ build.pl 

Scaled textures loads almost all files into the Plugins folder so that on demand loading works.
This includes all biomes.

### CODE REVIEW

**Comment by eggrobin** [comment]
The diff is too big for GitHub, but the readme changes can be seen at https://github.com/KSP-RO/RSS-Textures/pull/16/files/98f1b2fba381e1c5bbebd2fddfb2f1cb9512bf91.
@pap1723, you made the Scaled RSS textures, can you review this?

**Comment by pap1723** [comment]
What do I need to do to help with this one?

**Comment by eggrobin** [comment]
@Bornholio, there seems to be a copy of the 4096 directory in the 2048 directory, this looks like a mistake. As for the perl script, let's ignore it, it will be easier to zip things for release by hand.

@pap1723, just confirm that the directory structure makes sense; GitHub refuses to show a diff, but here is the tree after this pull request is merged (note the strange 4096 in the 2048 directory):
<details>
<summary>Click to expand…</summary>

```
│
├───2048
│   │   EarthColor.dds
│   │   Earth_NRM.dds
│   │   MoonColor.dds
│   │   Moon_NRM.dds
│   │   README.txt
│   │
│   ├───4096
│   │   │   EarthColor.dds
│   │   │   Earth_NRM.dds
│   │   │   MoonColor.dds
│   │   │   Moon_NRM.dds
│   │   │
│   │   └───PluginData
│   │           ArielBiomes.png
│   │           ArielColor.dds
│   │           ArielHeight.png
│   │           ArielNormal.png
│   │           CallistoBiomes.png
│   │           CallistoColor.dds
│   │           CallistoHeight.dds
│   │           Callisto_NRM.dds
│   │           CeresBiomes.png
│   │           CeresColor.dds
│   │           CeresHeight.png
│   │           CeresNormal.png
│   │           CharonBiomes.png
│   │           CharonColor.dds
│   │           CharonHeight.dds
│   │           Charon_NRM.dds
│   │           DeimosBiomes.png
│   │           DeimosColor.dds
│   │           DeimosHeight.dds
│   │           Deimos_NRM.dds
│   │           DioneBiomes.png
│   │           DioneColor.dds
│   │           EarthBiomes.png
│   │           EarthHeight.dds
│   │           EarthSurface.dds
│   │           EnceladusBiomes.png
│   │           EnceladusColor.dds
│   │           EuropaBiomes.png
│   │           EuropaColor.dds
│   │           EuropaHeight.dds
│   │           Europa_NRM.dds
│   │           Flat_NRM.dds
│   │           GanymedeBiomes.png
│   │           GanymedeColor.dds
│   │           GanymedeHeight.dds
│   │           Ganymede_NRM.dds
│   │           IapetusBiomes.png
│   │           IapetusColor.dds
│   │           IoBiomes.png
│   │           IoColor.dds
│   │           IoHeight.dds
│   │           Io_NRM.dds
│   │           JupiterBiomes.png
│   │           JupiterColor.dds
│   │           MarsBiomes.png
│   │           MarsColor.dds
│   │           MarsHeight.dds
│   │           Mars_NRM.dds
│   │           MercuryBiomes.png
│   │           MercuryColor.dds
│   │           MercuryHeight.dds
│   │           Mercury_NRM.dds
│   │           MimasBiomes.png
│   │           MimasColor.dds
│   │           MirandaBiomes.png
│   │           MirandaColor.dds
│   │           MirandaHeight.png
│   │           MirandaNormal.png
│   │           MoonBiomes.png
│   │           MoonHeight.dds
│   │           NeptuneBiomes.png
│   │           NeptuneColor.dds
│   │           OberonBiomes.png
│   │           OberonColor.dds
│   │           OberonHeight.png
│   │           OberonNormal.png
│   │           PhobosBiomes.png
│   │           PhobosColor.dds
│   │           PhobosHeight.dds
│   │           Phobos_NRM.dds
│   │           PlutoBiomes.png
│   │           PlutoColor.dds
│   │           PlutoHeight.dds
│   │           Pluto_NRM.dds
│   │           RheaBiomes.png
│   │           RheaColor.dds
│   │           SaturnBiomes.png
│   │           SaturnColor.dds
│   │           SaturnRing.dds
│   │           TethysBiomes.png
│   │           TethysColor.dds
│   │           TitanBiomes.png
│   │           TitanColor.dds
│   │           TitanHeight.dds
│   │           TitaniaBiomes.png
│   │           TitaniaColor.dds
│   │           TitaniaHeight.png
│   │           TitaniaNormal.png
│   │           Titan_NRM.dds
│   │           TritonBiomes.png
│   │           TritonColor.dds
│   │           UmbrielBiomes.png
│   │           UmbrielColor.dds
│   │           UmbrielHeight.png
│   │           UmbrielNormal.png
│   │           UranusBiomes.png
│   │           UranusColor.dds
│   │           VenusBiomes.png
│   │           VenusColor.dds
│   │           VenusHeight.dds
│   │           Venus_NRM.dds
│   │           VestaBiomes.png
│   │           VestaColor.png
│   │           VestaHeight.png
│   │           VestaNormal.png
│   │
│   └───PluginData
│           ArielBiomes.png
│           ArielColor.dds
│           ArielHeight.png
│           ArielNormal.png
│           CallistoBiomes.png
│           CallistoColor.dds
│           CallistoHeight.dds
│           Callisto_NRM.dds
│           CeresBiomes.png
│           CeresColor.dds
│           CeresHeight.png
│           CeresNormal.png
│           CharonBiomes.png
│           CharonColor.dds
│           CharonHeight.dds
│           Charon_NRM.dds
│           DeimosBiomes.png
│           DeimosColor.dds
│           DeimosHeight.dds
│           Deimos_NRM.dds
│           DioneBiomes.png
│           DioneColor.dds
│           EarthBiomes.png
│           EarthHeight.dds
│           EarthSurface.dds
│           EnceladusBiomes.png
│           EnceladusColor.dds
│           EuropaBiomes.png
│           EuropaColor.dds
│           EuropaHeight.dds
│           Europa_NRM.dds
│           Flat_NRM.dds
│           GanymedeBiomes.png
│           GanymedeColor.dds
│           GanymedeHeight.dds
│           Ganymede_NRM.dds
│           IapetusBiomes.png
│           IapetusColor.dds
│           IoBiomes.png
│           IoColor.dds
│           IoHeight.dds
│           Io_NRM.dds
│           JupiterBiomes.png
│           JupiterColor.dds
│           MarsBiomes.png
│           MarsColor.dds
│           MarsHeight.dds
│           Mars_NRM.dds
│           MercuryBiomes.png
│           MercuryColor.dds
│           MercuryHeight.dds
│           Mercury_NRM.dds
│           MimasBiomes.png
│           MimasColor.dds
│           MirandaBiomes.png
│           MirandaColor.dds
│           MirandaHeight.png
│           MirandaNormal.png
│           MoonBiomes.png
│           MoonHeight.dds
│           NeptuneBiomes.png
│           NeptuneColor.dds
│           OberonBiomes.png
│           OberonColor.dds
│           OberonHeight.png
│           OberonNormal.png
│           PhobosBiomes.png
│           PhobosColor.dds
│           PhobosHeight.dds
│           Phobos_NRM.dds
│           PlutoBiomes.png
│           PlutoColor.dds
│           PlutoHeight.dds
│           Pluto_NRM.dds
│           README.txt
│           RheaBiomes.png
│           RheaColor.dds
│           SaturnBiomes.png
│           SaturnColor.dds
│           SaturnRing.dds
│           TethysBiomes.png
│           TethysColor.dds
│           TitanBiomes.png
│           TitanColor.dds
│           TitanHeight.dds
│           TitaniaBiomes.png
│           TitaniaColor.dds
│           TitaniaHeight.png
│           TitaniaNormal.png
│           Titan_NRM.dds
│           TritonBiomes.png
│           TritonColor.dds
│           UmbrielBiomes.png
│           UmbrielColor.dds
│           UmbrielHeight.png
│           UmbrielNormal.png
│           UranusBiomes.png
│           UranusColor.dds
│           VenusBiomes.png
│           VenusColor.dds
│           VenusHeight.dds
│           Venus_NRM.dds
│           VestaBiomes.png
│           VestaColor.png
│           VestaHeight.png
│           VestaNormal.png
│
├───4096
│   │   EarthColor.dds
│   │   Earth_NRM.dds
│   │   MoonColor.dds
│   │   Moon_NRM.dds
│   │   README.txt
│   │
│   └───PluginData
│           ArielBiomes.png
│           ArielColor.dds
│           ArielHeight.png
│           ArielNormal.png
│           CallistoBiomes.png
│           CallistoColor.dds
│           CallistoHeight.dds
│           Callisto_NRM.dds
│           CeresBiomes.png
│           CeresColor.dds
│           CeresHeight.png
│           CeresNormal.png
│           CharonBiomes.png
│           CharonColor.dds
│           CharonHeight.dds
│           Charon_NRM.dds
│           DeimosBiomes.png
│           DeimosColor.dds
│           DeimosHeight.dds
│           Deimos_NRM.dds
│           DioneBiomes.png
│           DioneColor.dds
│           EarthBiomes.png
│           EarthHeight.dds
│           EarthSurface.dds
│           EnceladusBiomes.png
│           EnceladusColor.dds
│           EuropaBiomes.png
│           EuropaColor.dds
│           EuropaHeight.dds
│           Europa_NRM.dds
│           Flat_NRM.dds
│           GanymedeBiomes.png
│           GanymedeColor.dds
│           GanymedeHeight.dds
│           Ganymede_NRM.dds
│           IapetusBiomes.png
│           IapetusColor.dds
│           IoBiomes.png
│           IoColor.dds
│           IoHeight.dds
│           Io_NRM.dds
│           JupiterBiomes.png
│           JupiterColor.dds
│           MarsBiomes.png
│           MarsColor.dds
│           MarsHeight.dds
│           Mars_NRM.dds
│           MercuryBiomes.png
│           MercuryColor.dds
│           MercuryHeight.dds
│           Mercury_NRM.dds
│           MimasBiomes.png
│           MimasColor.dds
│           MirandaBiomes.png
│           MirandaColor.dds
│           MirandaHeight.png
│           MirandaNormal.png
│           MoonBiomes.png
│           MoonHeight.dds
│           NeptuneBiomes.png
│           NeptuneColor.dds
│           OberonBiomes.png
│           OberonColor.dds
│           OberonHeight.png
│           OberonNormal.png
│           PhobosBiomes.png
│           PhobosColor.dds
│           PhobosHeight.dds
│           Phobos_NRM.dds
│           PlutoBiomes.png
│           PlutoColor.dds
│           PlutoHeight.dds
│           Pluto_NRM.dds
│           RheaBiomes.png
│           RheaColor.dds
│           SaturnBiomes.png
│           SaturnColor.dds
│           SaturnRing.dds
│           TethysBiomes.png
│           TethysColor.dds
│           TitanBiomes.png
│           TitanColor.dds
│           TitanHeight.dds
│           TitaniaBiomes.png
│           TitaniaColor.dds
│           TitaniaHeight.png
│           TitaniaNormal.png
│           Titan_NRM.dds
│           TritonBiomes.png
│           TritonColor.dds
│           UmbrielBiomes.png
│           UmbrielColor.dds
│           UmbrielHeight.png
│           UmbrielNormal.png
│           UranusBiomes.png
│           UranusColor.dds
│           VenusBiomes.png
│           VenusColor.dds
│           VenusHeight.dds
│           Venus_NRM.dds
│           VestaBiomes.png
│           VestaColor.png
│           VestaHeight.png
│           VestaNormal.png
│
├───8192
│   │   EarthColor.dds
│   │   Earth_NRM.dds
│   │   MoonColor.dds
│   │   Moon_NRM.dds
│   │   README.txt
│   │
│   └───PluginData
│           ArielBiomes.png
│           ArielColor.dds
│           ArielHeight.png
│           ArielNormal.png
│           CallistoBiomes.png
│           CallistoColor.dds
│           CallistoHeight.dds
│           Callisto_NRM.dds
│           CeresBiomes.png
│           CeresColor.dds
│           CeresHeight.png
│           CeresNormal.png
│           CharonBiomes.png
│           CharonColor.dds
│           CharonHeight.dds
│           Charon_NRM.dds
│           DeimosBiomes.png
│           DeimosColor.dds
│           DeimosHeight.dds
│           Deimos_NRM.dds
│           DioneBiomes.png
│           DioneColor.dds
│           EarthBiomes.png
│           EarthHeight.dds
│           EarthSurface.dds
│           EnceladusBiomes.png
│           EnceladusColor.dds
│           EuropaBiomes.png
│           EuropaColor.dds
│           EuropaHeight.dds
│           Europa_NRM.dds
│           Flat_NRM.dds
│           GanymedeBiomes.png
│           GanymedeColor.dds
│           GanymedeHeight.dds
│           Ganymede_NRM.dds
│           IapetusBiomes.png
│           IapetusColor.dds
│           IoBiomes.png
│           IoColor.dds
│           IoHeight.dds
│           Io_NRM.dds
│           JupiterBiomes.png
│           JupiterColor.dds
│           MarsBiomes.png
│           MarsColor.dds
│           MarsHeight.dds
│           Mars_NRM.dds
│           MercuryBiomes.png
│           MercuryColor.dds
│           MercuryHeight.dds
│           Mercury_NRM.dds
│           MimasBiomes.png
│           MimasColor.dds
│           MirandaBiomes.png
│           MirandaColor.dds
│           MirandaHeight.png
│           MirandaNormal.png
│           MoonBiomes.png
│           MoonHeight.dds
│           NeptuneBiomes.png
│           NeptuneColor.dds
│           OberonBiomes.png
│           OberonColor.dds
│           OberonHeight.png
│           OberonNormal.png
│           PhobosBiomes.png
│           PhobosColor.dds
│           PhobosHeight.dds
│           Phobos_NRM.dds
│           PlutoBiomes.png
│           PlutoColor.dds
│           PlutoHeight.dds
│           Pluto_NRM.dds
│           README.txt
│           RheaBiomes.png
│           RheaColor.dds
│           SaturnBiomes.png
│           SaturnColor.dds
│           SaturnRing.dds
│           TethysBiomes.png
│           TethysColor.dds
│           TitanBiomes.png
│           TitanColor.dds
│           TitanHeight.dds
│           TitaniaBiomes.png
│           TitaniaColor.dds
│           TitaniaHeight.png
│           TitaniaNormal.png
│           Titan_NRM.dds
│           TritonBiomes.png
│           TritonColor.dds
│           UmbrielBiomes.png
│           UmbrielColor.dds
│           UmbrielHeight.png
│           UmbrielNormal.png
│           UranusBiomes.png
│           UranusColor.dds
│           VenusBiomes.png
│           VenusColor.dds
│           VenusHeight.dds
│           Venus_NRM.dds
│           VestaBiomes.png
│           VestaColor.png
│           VestaHeight.png
│           VestaNormal.png
│
└───bin
        build.pl
```

</details>

**Comment by eggrobin** [comment]
@Bornholio, there seems to be a copy of the 4096 directory in the 2048 directory, this looks like a mistake. As for perl script, let's ignore it, it will be easier to zip things for release by hand.

@pap1723, just confirm that the directory structure makes sense; GitHub refuses to show a diff, but here is the tree after this pull request is merged (note the strange 4096 in the 2048 directory):
```
│
├───2048
│   │   EarthColor.dds
│   │   Earth_NRM.dds
│   │   MoonColor.dds
│   │   Moon_NRM.dds
│   │   README.txt
│   │
│   ├───4096
│   │   │   EarthColor.dds
│   │   │   Earth_NRM.dds
│   │   │   MoonColor.dds
│   │   │   Moon_NRM.dds
│   │   │
│   │   └───PluginData
│   │           ArielBiomes.png
│   │           ArielColor.dds
│   │           ArielHeight.png
│   │           ArielNormal.png
│   │           CallistoBiomes.png
│   │           CallistoColor.dds
│   │           CallistoHeight.dds
│   │           Callisto_NRM.dds
│   │           CeresBiomes.png
│   │           CeresColor.dds
│   │           CeresHeight.png
│   │           CeresNormal.png
│   │           CharonBiomes.png
│   │           CharonColor.dds
│   │           CharonHeight.dds
│   │           Charon_NRM.dds
│   │           DeimosBiomes.png
│   │           DeimosColor.dds
│   │           DeimosHeight.dds
│   │           Deimos_NRM.dds
│   │           DioneBiomes.png
│   │           DioneColor.dds
│   │           EarthBiomes.png
│   │           EarthHeight.dds
│   │           EarthSurface.dds
│   │           EnceladusBiomes.png
│   │           EnceladusColor.dds
│   │           EuropaBiomes.png
│   │           EuropaColor.dds
│   │           EuropaHeight.dds
│   │           Europa_NRM.dds
│   │           Flat_NRM.dds
│   │           GanymedeBiomes.png
│   │           GanymedeColor.dds
│   │           GanymedeHeight.dds
│   │           Ganymede_NRM.dds
│   │           IapetusBiomes.png
│   │           IapetusColor.dds
│   │           IoBiomes.png
│   │           IoColor.dds
│   │           IoHeight.dds
│   │           Io_NRM.dds
│   │           JupiterBiomes.png
│   │           JupiterColor.dds
│   │           MarsBiomes.png
│   │           MarsColor.dds
│   │           MarsHeight.dds
│   │           Mars_NRM.dds
│   │           MercuryBiomes.png
│   │           MercuryColor.dds
│   │           MercuryHeight.dds
│   │           Mercury_NRM.dds
│   │           MimasBiomes.png
│   │           MimasColor.dds
│   │           MirandaBiomes.png
│   │           MirandaColor.dds
│   │           MirandaHeight.png
│   │           MirandaNormal.png
│   │           MoonBiomes.png
│   │           MoonHeight.dds
│   │           NeptuneBiomes.png
│   │           NeptuneColor.dds
│   │           OberonBiomes.png
│   │           OberonColor.dds
│   │           OberonHeight.png
│   │           OberonNormal.png
│   │           PhobosBiomes.png
│   │           PhobosColor.dds
│   │           PhobosHeight.dds
│   │           Phobos_NRM.dds
│   │           PlutoBiomes.png
│   │           PlutoColor.dds
│   │           PlutoHeight.dds
│   │           Pluto_NRM.dds
│   │           RheaBiomes.png
│   │           RheaColor.dds
│   │           SaturnBiomes.png
│   │           SaturnColor.dds
│   │           SaturnRing.dds
│   │           TethysBiomes.png
│   │           TethysColor.dds
│   │           TitanBiomes.png
│   │           TitanColor.dds
│   │           TitanHeight.dds
│   │           TitaniaBiomes.png
│   │           TitaniaColor.dds
│   │           TitaniaHeight.png
│   │           TitaniaNormal.png
│   │           Titan_NRM.dds
│   │           TritonBiomes.png
│   │           TritonColor.dds
│   │           UmbrielBiomes.png
│   │           UmbrielColor.dds
│   │           UmbrielHeight.png
│   │           UmbrielNormal.png
│   │           UranusBiomes.png
│   │           UranusColor.dds
│   │           VenusBiomes.png
│   │           VenusColor.dds
│   │           VenusHeight.dds
│   │           Venus_NRM.dds
│   │           VestaBiomes.png
│   │           VestaColor.png
│   │           VestaHeight.png
│   │           VestaNormal.png
│   │
│   └───PluginData
│           ArielBiomes.png
│           ArielColor.dds
│           ArielHeight.png
│           ArielNormal.png
│           CallistoBiomes.png
│           CallistoColor.dds
│           CallistoHeight.dds
│           Callisto_NRM.dds
│           CeresBiomes.png
│           CeresColor.dds
│           CeresHeight.png
│           CeresNormal.png
│           CharonBiomes.png
│           CharonColor.dds
│           CharonHeight.dds
│           Charon_NRM.dds
│           DeimosBiomes.png
│           DeimosColor.dds
│           DeimosHeight.dds
│           Deimos_NRM.dds
│           DioneBiomes.png
│           DioneColor.dds
│           EarthBiomes.png
│           EarthHeight.dds
│           EarthSurface.dds
│           EnceladusBiomes.png
│           EnceladusColor.dds
│           EuropaBiomes.png
│           EuropaColor.dds
│           EuropaHeight.dds
│           Europa_NRM.dds
│           Flat_NRM.dds
│           GanymedeBiomes.png
│           GanymedeColor.dds
│           GanymedeHeight.dds
│           Ganymede_NRM.dds
│           IapetusBiomes.png
│           IapetusColor.dds
│           IoBiomes.png
│           IoColor.dds
│           IoHeight.dds
│           Io_NRM.dds
│           JupiterBiomes.png
│           JupiterColor.dds
│           MarsBiomes.png
│           MarsColor.dds
│           MarsHeight.dds
│           Mars_NRM.dds
│           MercuryBiomes.png
│           MercuryColor.dds
│           MercuryHeight.dds
│           Mercury_NRM.dds
│           MimasBiomes.png
│           MimasColor.dds
│           MirandaBiomes.png
│           MirandaColor.dds
│           MirandaHeight.png
│           MirandaNormal.png
│           MoonBiomes.png
│           MoonHeight.dds
│           NeptuneBiomes.png
│           NeptuneColor.dds
│           OberonBiomes.png
│           OberonColor.dds
│           OberonHeight.png
│           OberonNormal.png
│           PhobosBiomes.png
│           PhobosColor.dds
│           PhobosHeight.dds
│           Phobos_NRM.dds
│           PlutoBiomes.png
│           PlutoColor.dds
│           PlutoHeight.dds
│           Pluto_NRM.dds
│           README.txt
│           RheaBiomes.png
│           RheaColor.dds
│           SaturnBiomes.png
│           SaturnColor.dds
│           SaturnRing.dds
│           TethysBiomes.png
│           TethysColor.dds
│           TitanBiomes.png
│           TitanColor.dds
│           TitanHeight.dds
│           TitaniaBiomes.png
│           TitaniaColor.dds
│           TitaniaHeight.png
│           TitaniaNormal.png
│           Titan_NRM.dds
│           TritonBiomes.png
│           TritonColor.dds
│           UmbrielBiomes.png
│           UmbrielColor.dds
│           UmbrielHeight.png
│           UmbrielNormal.png
│           UranusBiomes.png
│           UranusColor.dds
│           VenusBiomes.png
│           VenusColor.dds
│           VenusHeight.dds
│           Venus_NRM.dds
│           VestaBiomes.png
│           VestaColor.png
│           VestaHeight.png
│           VestaNormal.png
│
├───4096
│   │   EarthColor.dds
│   │   Earth_NRM.dds
│   │   MoonColor.dds
│   │   Moon_NRM.dds
│   │   README.txt
│   │
│   └───PluginData
│           ArielBiomes.png
│           ArielColor.dds
│           ArielHeight.png
│           ArielNormal.png
│           CallistoBiomes.png
│           CallistoColor.dds
│           CallistoHeight.dds
│           Callisto_NRM.dds
│           CeresBiomes.png
│           CeresColor.dds
│           CeresHeight.png
│           CeresNormal.png
│           CharonBiomes.png
│           CharonColor.dds
│           CharonHeight.dds
│           Charon_NRM.dds
│           DeimosBiomes.png
│           DeimosColor.dds
│           DeimosHeight.dds
│           Deimos_NRM.dds
│           DioneBiomes.png
│           DioneColor.dds
│           EarthBiomes.png
│           EarthHeight.dds
│           EarthSurface.dds
│           EnceladusBiomes.png
│           EnceladusColor.dds
│           EuropaBiomes.png
│           EuropaColor.dds
│           EuropaHeight.dds
│           Europa_NRM.dds
│           Flat_NRM.dds
│           GanymedeBiomes.png
│           GanymedeColor.dds
│           GanymedeHeight.dds
│           Ganymede_NRM.dds
│           IapetusBiomes.png
│           IapetusColor.dds
│           IoBiomes.png
│           IoColor.dds
│           IoHeight.dds
│           Io_NRM.dds
│           JupiterBiomes.png
│           JupiterColor.dds
│           MarsBiomes.png
│           MarsColor.dds
│           MarsHeight.dds
│           Mars_NRM.dds
│           MercuryBiomes.png
│           MercuryColor.dds
│           MercuryHeight.dds
│           Mercury_NRM.dds
│           MimasBiomes.png
│           MimasColor.dds
│           MirandaBiomes.png
│           MirandaColor.dds
│           MirandaHeight.png
│           MirandaNormal.png
│           MoonBiomes.png
│           MoonHeight.dds
│           NeptuneBiomes.png
│           NeptuneColor.dds
│           OberonBiomes.png
│           OberonColor.dds
│           OberonHeight.png
│           OberonNormal.png
│           PhobosBiomes.png
│           PhobosColor.dds
│           PhobosHeight.dds
│           Phobos_NRM.dds
│           PlutoBiomes.png
│           PlutoColor.dds
│           PlutoHeight.dds
│           Pluto_NRM.dds
│           RheaBiomes.png
│           RheaColor.dds
│           SaturnBiomes.png
│           SaturnColor.dds
│           SaturnRing.dds
│           TethysBiomes.png
│           TethysColor.dds
│           TitanBiomes.png
│           TitanColor.dds
│           TitanHeight.dds
│           TitaniaBiomes.png
│           TitaniaColor.dds
│           TitaniaHeight.png
│           TitaniaNormal.png
│           Titan_NRM.dds
│           TritonBiomes.png
│           TritonColor.dds
│           UmbrielBiomes.png
│           UmbrielColor.dds
│           UmbrielHeight.png
│           UmbrielNormal.png
│           UranusBiomes.png
│           UranusColor.dds
│           VenusBiomes.png
│           VenusColor.dds
│           VenusHeight.dds
│           Venus_NRM.dds
│           VestaBiomes.png
│           VestaColor.png
│           VestaHeight.png
│           VestaNormal.png
│
├───8192
│   │   EarthColor.dds
│   │   Earth_NRM.dds
│   │   MoonColor.dds
│   │   Moon_NRM.dds
│   │   README.txt
│   │
│   └───PluginData
│           ArielBiomes.png
│           ArielColor.dds
│           ArielHeight.png
│           ArielNormal.png
│           CallistoBiomes.png
│           CallistoColor.dds
│           CallistoHeight.dds
│           Callisto_NRM.dds
│           CeresBiomes.png
│           CeresColor.dds
│           CeresHeight.png
│           CeresNormal.png
│           CharonBiomes.png
│           CharonColor.dds
│           CharonHeight.dds
│           Charon_NRM.dds
│           DeimosBiomes.png
│           DeimosColor.dds
│           DeimosHeight.dds
│           Deimos_NRM.dds
│           DioneBiomes.png
│           DioneColor.dds
│           EarthBiomes.png
│           EarthHeight.dds
│           EarthSurface.dds
│           EnceladusBiomes.png
│           EnceladusColor.dds
│           EuropaBiomes.png
│           EuropaColor.dds
│           EuropaHeight.dds
│           Europa_NRM.dds
│           Flat_NRM.dds
│           GanymedeBiomes.png
│           GanymedeColor.dds
│           GanymedeHeight.dds
│           Ganymede_NRM.dds
│           IapetusBiomes.png
│           IapetusColor.dds
│           IoBiomes.png
│           IoColor.dds
│           IoHeight.dds
│           Io_NRM.dds
│           JupiterBiomes.png
│           JupiterColor.dds
│           MarsBiomes.png
│           MarsColor.dds
│           MarsHeight.dds
│           Mars_NRM.dds
│           MercuryBiomes.png
│           MercuryColor.dds
│           MercuryHeight.dds
│           Mercury_NRM.dds
│           MimasBiomes.png
│           MimasColor.dds
│           MirandaBiomes.png
│           MirandaColor.dds
│           MirandaHeight.png
│           MirandaNormal.png
│           MoonBiomes.png
│           MoonHeight.dds
│           NeptuneBiomes.png
│           NeptuneColor.dds
│           OberonBiomes.png
│           OberonColor.dds
│           OberonHeight.png
│           OberonNormal.png
│           PhobosBiomes.png
│           PhobosColor.dds
│           PhobosHeight.dds
│           Phobos_NRM.dds
│           PlutoBiomes.png
│           PlutoColor.dds
│           PlutoHeight.dds
│           Pluto_NRM.dds
│           README.txt
│           RheaBiomes.png
│           RheaColor.dds
│           SaturnBiomes.png
│           SaturnColor.dds
│           SaturnRing.dds
│           TethysBiomes.png
│           TethysColor.dds
│           TitanBiomes.png
│           TitanColor.dds
│           TitanHeight.dds
│           TitaniaBiomes.png
│           TitaniaColor.dds
│           TitaniaHeight.png
│           TitaniaNormal.png
│           Titan_NRM.dds
│           TritonBiomes.png
│           TritonColor.dds
│           UmbrielBiomes.png
│           UmbrielColor.dds
│           UmbrielHeight.png
│           UmbrielNormal.png
│           UranusBiomes.png
│           UranusColor.dds
│           VenusBiomes.png
│           VenusColor.dds
│           VenusHeight.dds
│           Venus_NRM.dds
│           VestaBiomes.png
│           VestaColor.png
│           VestaHeight.png
│           VestaNormal.png
│
└───bin
        build.pl
```

**Comment by Bornholio** [comment]
okay, how do we delete a folder in github?

**Comment by pap1723** [comment]
Yes, the structure looks correct.

**Comment by eggrobin** [comment]
Sounds good, deleting the extraneous 4096 and merging.

**Comment by eggrobin** [comment]
[merged on the command line, which seems to have confused GitHub as to the state of this pull request]

**Pull request closed without merging**
