### PR TITLE
Remastered biomes

### PR DESCRIPTION
**Pull request by RCrockford**
Remastered biomes from original pngs to elimiate DXT errors that had crept in.

### CODE REVIEW

**Comment by siimav** [comment]
Did you reconvert the biome maps to a lossless format?

**Comment by RCrockford** [comment]
Yes, they should all be uncompressed now. There's no benefit to compressing biome Maria as they are uncompressed in load anyway.

**Comment by siimav** [comment]
RSS doesn't load up for me with those new biome maps.
`[LOG 21:51:50]: [Kopernicus]: Configuration.Loader: Failed to load Body: Jupiter: The Biome Map cannot be null if you want to add biomes.`

**Comment by RCrockford** [comment]
Should all be working with release Kopernicus.

**Comment by siimav** [comment]
Now I'm not getting any biomes at all. Also, nothing changes if I enable the Show Biomes option from the cheat menu.

**Comment by siimav** [comment]
With there being Kopernicus backports for KSP 1.8.1 now, is this safe to merge? Would need a conflict cleanup first though.

**Comment by NathanKell** [comment]
Bumping this -- still needed?

**Pull request merged**
